apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - image: bitnami/kubewatch #using this image, its more stable and active
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: conf