apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace:
    handler:
      msteams:
        webhookurl: https://outlook.office.com/webhook/...
    resource:
      namespace